/**
 * Writes `src/icons.generated.ts`: the path data of the Material Symbols Outlined glyphs the
 * catalog offers, outlined and filled, at the 24 px optical size. Material Symbols is Apache-2.0,
 * from google/material-design-icons at a pinned commit.
 *
 *   node scripts/generate-icons.mjs
 */
import {writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const COMMIT = 'bd8cb85bd4bad964fe6918f79665bb40c3a8efef';
const ICONS = [
  'add',
  'arrow_back',
  'calendar_today',
  'cancel',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'content_copy',
  'edit',
  'error',
  'event',
  'event_available',
  'event_busy',
  'expand_less',
  'expand_more',
  'group',
  'help',
  'info',
  'location_on',
  'lock',
  'mail',
  'meeting_room',
  'more_vert',
  'notes',
  'notifications',
  'person',
  'refresh',
  'repeat',
  'schedule',
  'search',
  'today',
  'videocam',
  'warning',
];

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const base = `https://raw.githubusercontent.com/google/material-design-icons/${COMMIT}/symbols/web`;

async function pathOf(name, file) {
  const response = await globalThis.fetch(`${base}/${name}/materialsymbolsoutlined/${file}`);
  if (!response.ok) throw new Error(`${name}: ${response.status} for ${file}`);
  const svg = await response.text();
  const paths = [...svg.matchAll(/<path d="([^"]+)"/g)].map(match => match[1]);
  if (paths.length === 0) throw new Error(`${name}: no path in ${file}`);
  return paths.join(' ');
}

const entries = [];
for (const name of ICONS) {
  const outlined = await pathOf(name, `${name}_24px.svg`);
  const filled = await pathOf(name, `${name}_fill1_24px.svg`);
  entries.push(`  ${name}: {outlined: '${outlined}', filled: '${filled}'},`);
}

const ts = `/**
 * Generated by scripts/generate-icons.mjs; do not edit by hand. Material Symbols Outlined at the
 * 24 px optical size (viewBox 0 -960 960 960), from google/material-design-icons@${COMMIT.slice(0, 7)},
 * Apache License 2.0.
 */
export const ICON_PATHS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICON_PATHS;

export const ICON_NAMES = Object.keys(ICON_PATHS) as IconName[];
`;

writeFileSync(resolve(packageRoot, 'src/icons.generated.ts'), ts);
